document.addEventListener('DOMContentLoaded',()=>{const KEY='nbh_offer_check_v1',$=x=>document.getElementById(x),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const checks=[
['identity','Produktidentität','GTIN/Modell/Variante sind eindeutig und passen zum Vergleich.','critical'],
['total','Gesamtpreis','Produktpreis, Versand und sonstige Pflichtkosten sind vollständig berücksichtigt.','critical'],
['seller','Verkäufer','Der tatsächliche Vertragspartner/Marktplatz-Verkäufer ist klar erkennbar.','critical'],
['condition','Zustand','Neu, B-Ware, refurbished oder gebraucht ist eindeutig angegeben.','normal'],
['availability','Verfügbarkeit','Lieferbarkeit und Lieferzeit sind aktuell und nachvollziehbar.','normal'],
['returns','Rückgabe','Rückgabebedingungen und mögliche Rücksendekosten wurden geprüft.','normal'],
['service','Gewährleistung / Service','Serviceweg, Garantiehinweise oder Ansprechpartner sind soweit relevant geklärt.','normal'],
['payment','Zahlung','Zahlungsweg, Zeitpunkt und mögliche Zusatzkosten sind klar.','normal']];
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}},save=o=>localStorage.setItem(KEY,JSON.stringify(o));
function build(){const old=load();$('ocName').value=old.name||'';$('ocMerchant').value=old.merchant||'';$('ocUrl').value=old.url||'';$('ocTotal').value=old.total||'';$('ocNote').value=old.note||'';$('offerCheckGrid').innerHTML=checks.map(([id,title,help,level])=>`<fieldset class="offer-check-item" data-level="${level}"><legend>${title}</legend><p>${help}</p><div class="tri-state" role="radiogroup" aria-label="${title}">${[['yes','Geklärt'],['unknown','Offen'],['no','Auffällig']].map(([v,l])=>`<label><input type="radio" name="oc_${id}" value="${v}" ${(old.checks?.[id]||'unknown')===v?'checked':''}>${l}</label>`).join('')}</div></fieldset>`).join('');if(old.savedAt)evaluate(false)}
function data(){const out={name:$('ocName').value.trim(),merchant:$('ocMerchant').value.trim(),url:$('ocUrl').value.trim(),total:parseFloat($('ocTotal').value)||0,note:$('ocNote').value.trim(),checks:{},savedAt:new Date().toISOString()};checks.forEach(([id])=>out.checks[id]=document.querySelector(`input[name="oc_${id}"]:checked`)?.value||'unknown');return out}
function evaluate(store=true){const d=data();if(store)save(d);const vals=Object.values(d.checks),ok=vals.filter(x=>x==='yes').length,open=vals.filter(x=>x==='unknown').length,bad=vals.filter(x=>x==='no').length,crit=checks.filter(([id,,,level])=>level==='critical'&&d.checks[id]!=='yes').map(x=>x[1]);let cls=bad?'bad':open?'neutral':'good';let title=bad?`${bad} auffällige Punkte`:open?`${open} Punkte noch offen`:'Alle Prüfpunkte geklärt';let details=[];if(crit.length)details.push(`<span><b>Besonders wichtig:</b> ${crit.map(esc).join(', ')} noch nicht sauber geklärt.</span>`);details.push(`<span>${ok} von ${checks.length} Punkten geklärt · ${open} offen · ${bad} auffällig.</span>`);if(d.total>0)details.push(`<span>Eingetragener Gesamtpreis: ${new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(d.total)}.</span>`);$('ocResult').className='tool-result '+cls;$('ocResult').innerHTML=`<strong>${title}</strong>${details.join('')}`;return d}
$('offerCheckForm').onsubmit=e=>{e.preventDefault();evaluate(true);NBH?.toast?.('Angebots-Check lokal gespeichert')};$('ocReset').onclick=()=>{if(confirm('Gespeicherten Angebots-Check zurücksetzen?')){localStorage.removeItem(KEY);location.reload()}};$('ocExport').onclick=()=>{const d=evaluate(false),lines=['NBHandel Angebots-Check',d.name?`Bezeichnung: ${d.name}`:'',d.merchant?`Händler/Verkäufer: ${d.merchant}`:'',d.url?`URL: ${d.url}`:'',d.total?`Gesamtpreis: ${d.total.toFixed(2)} EUR`:'','',...checks.map(([id,title])=>`${title}: ${{yes:'Geklärt',unknown:'Offen',no:'Auffällig'}[d.checks[id]]}`),'',d.note?`Notiz: ${d.note}`:''].filter(Boolean);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}));a.download='nbhandel-angebotscheck.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};build()});