document.addEventListener('DOMContentLoaded',()=>{
  const eur=new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'});
  const n=v=>{const x=parseFloat(String(v??'').replace(',','.'));return Number.isFinite(x)?x:0};
  const $=id=>document.getElementById(id);
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const result=(id,html,kind='neutral')=>{const el=$(id);if(!el)return;el.className='tool-result '+kind;el.innerHTML=html};
  function gtin(code){code=String(code||'').replace(/[\s-]/g,'');if(!/^\d+$/.test(code))return{ok:false,msg:'Nur Ziffern sind zulässig.'};if(![8,12,13,14].includes(code.length))return{ok:false,msg:'Unterstützt werden EAN-8, GTIN-12/UPC-A, EAN-13 und GTIN-14.'};const body=code.slice(0,-1),check=Number(code.at(-1));let sum=0,w=3;for(let i=body.length-1;i>=0;i--){sum+=Number(body[i])*w;w=w===3?1:3}const expected=(10-sum%10)%10;const kind={8:'EAN-8',12:'GTIN-12 / UPC-A',13:'EAN-13',14:'GTIN-14'}[code.length];return{ok:check===expected,expected,kind,normalized:code.padStart(14,'0')}}
  $('gtinBtn')?.addEventListener('click',()=>{const r=gtin($('gtinInput').value);if(r.ok)result('gtinResult',`<strong>Formal gültig: ${r.kind}</strong><span>Prüfziffer stimmt. Normalisierte 14-stellige Schreibweise: <code>${r.normalized}</code>. Das bestätigt nicht, welches Produkt hinter der Nummer steht.</span>`,'good');else result('gtinResult',`<strong>Nicht gültig.</strong><span>${esc(r.msg||`Erwartete Prüfziffer: ${r.expected}.`)}</span>`,'bad')});
  $('gpBtn')?.addEventListener('click',()=>{const p=n($('gpPrice').value),ship=n($('gpShip').value),extra=n($('gpExtra')?.value),q=Math.max(1,Math.floor(n($('gpQty').value)||1)),disc=n($('gpDiscount').value);if(p<=0)return result('gpResult','Bitte einen Artikelpreis größer 0 eingeben.','bad');const gross=p*q+ship+extra,total=Math.max(0,gross-disc),per=total/q;result('gpResult',`<strong>Gesamt: ${eur.format(total)}</strong><span>${q} Stück · ${eur.format(per)} pro Stück. Rechenweg: (${eur.format(p)} × ${q}) + ${eur.format(ship)} Versand + ${eur.format(extra)} Pflichtkosten − ${eur.format(disc)} Rabatt.</span>`,'good')});
  $('unitBtn')?.addEventListener('click',()=>{const p=n($('unitPrice').value),a=n($('unitAmount').value),t=$('unitType').value;if(p<=0||a<=0)return result('unitResult','Preis und Menge müssen größer 0 sein.','bad');let base,label;if(t==='g'){base=a/1000;label='kg'}else if(t==='kg'){base=a;label='kg'}else if(t==='ml'){base=a/1000;label='l'}else if(t==='l'){base=a;label='l'}else{base=a;label='Stück'}result('unitResult',`<strong>${eur.format(p/base)} pro ${label}</strong><span>Aus ${eur.format(p)} bei ${a.toLocaleString('de-DE')} ${t==='piece'?'Stück':t}.</span>`,'good')});
  const tbody=$('offerRows');if(tbody){['A','B','C','D'].forEach(x=>tbody.insertAdjacentHTML('beforeend',`<tr><td><input class="offer-name" value="Angebot ${x}" aria-label="Name Angebot ${x}"></td><td><input class="offer-price" type="number" min="0" step="0.01" aria-label="Preis Angebot ${x}"></td><td><input class="offer-ship" type="number" min="0" step="0.01" value="0" aria-label="Versand Angebot ${x}"></td><td><input class="offer-extra" type="number" min="0" step="0.01" value="0" aria-label="Pflichtkosten Angebot ${x}"></td><td><input class="offer-qty" type="number" min="1" step="1" value="1" aria-label="Menge Angebot ${x}"></td><td><select class="offer-condition" aria-label="Zustand Angebot ${x}"><option>Neu</option><option>B-Ware</option><option>Refurbished</option><option>Gebraucht</option><option>Unklar</option></select></td></tr>`))}
  $('offersBtn')?.addEventListener('click',()=>{const rows=[...document.querySelectorAll('#offerRows tr')].map(r=>{const name=r.querySelector('.offer-name').value.trim()||'Angebot',p=n(r.querySelector('.offer-price').value),ship=n(r.querySelector('.offer-ship').value),extra=n(r.querySelector('.offer-extra').value),q=Math.max(1,Math.floor(n(r.querySelector('.offer-qty').value)||1)),condition=r.querySelector('.offer-condition').value;return p>0?{name,p,ship,extra,q,condition,total:p*q+ship+extra,per:(p*q+ship+extra)/q}:null}).filter(Boolean);if(rows.length<2)return result('offersResult','Bitte mindestens zwei Angebote mit Preis eingeben.','bad');rows.sort((a,b)=>a.total-b.total);const conditions=new Set(rows.map(r=>r.condition));const warn=conditions.size>1?' <strong>Achtung:</strong> Die Zustände unterscheiden sich und sind nicht direkt gleichwertig.':'';result('offersResult',`<strong>Niedrigster Gesamtpreis: ${esc(rows[0].name)} – ${eur.format(rows[0].total)}</strong><div class="result-list">${rows.map((r,i)=>`<div><b>${i+1}. ${esc(r.name)}</b><span>${eur.format(r.total)} gesamt · ${eur.format(r.per)} pro Stück · ${esc(r.condition)}</span></div>`).join('')}</div><span>Nur sinnvoll, wenn Produkt und Lieferumfang vergleichbar sind.${warn}</span>`,'good')});
  $('offersReset')?.addEventListener('click',()=>{document.querySelectorAll('.offer-price').forEach(x=>x.value='');document.querySelectorAll('.offer-ship,.offer-extra').forEach(x=>x.value='0');document.querySelectorAll('.offer-qty').forEach(x=>x.value='1');document.querySelectorAll('.offer-condition').forEach(x=>x.value='Neu');result('offersResult','Noch kein Vergleich.','neutral')});

  $('discountBtn')?.addEventListener('click',()=>{const old=n($('discountOld').value),cur=n($('discountNow').value);if(old<=0||cur<0)return result('discountResult','Bitte gültige Preise eingeben.','bad');const diff=old-cur,pct=diff/old*100;result('discountResult',`<strong>${diff>=0?'Ersparnis':'Aufpreis'}: ${eur.format(Math.abs(diff))} (${Math.abs(pct).toFixed(1).replace('.',',')} %)</strong><span>Referenz: ${eur.format(old)} · aktuell: ${eur.format(cur)}.</span>`,diff>=0?'good':'bad')});
  $('changeBtn')?.addEventListener('click',()=>{const a=n($('changeOld').value),b=n($('changeNew').value);if(a<=0||b<0)return result('changeResult','Bitte gültige Werte eingeben.','bad');const d=b-a,p=d/a*100;result('changeResult',`<strong>${d>=0?'Anstieg':'Rückgang'}: ${eur.format(Math.abs(d))} (${Math.abs(p).toFixed(1).replace('.',',')} %)</strong><span>Von ${eur.format(a)} auf ${eur.format(b)}.</span>`,d<=0?'good':'neutral')});
  $('bundleBtn')?.addEventListener('click',()=>{const ap=n($('bundleAPrice').value),aq=n($('bundleAQty').value),bp=n($('bundleBPrice').value),bq=n($('bundleBQty').value);if(ap<=0||aq<=0||bp<=0||bq<=0)return result('bundleResult','Preise und Mengen müssen größer 0 sein.','bad');const au=ap/aq,bu=bp/bq,best=au<=bu?'A':'B';result('bundleResult',`<strong>Bundle ${best} ist pro Einheit günstiger.</strong><span>A: ${eur.format(au)} je Einheit · B: ${eur.format(bu)} je Einheit · Differenz ${eur.format(Math.abs(au-bu))}.</span>`,'good')});
  $('shipBtn')?.addEventListener('click',()=>{const cart=n($('shipCart').value),th=n($('shipThreshold').value),fee=n($('shipFee').value);if(cart<0||th<=0||fee<0)return result('shipResult','Bitte gültige Werte eingeben.','bad');const gap=Math.max(0,th-cart);if(gap===0)return result('shipResult','<strong>Schwelle bereits erreicht.</strong><span>Für diesen Warenkorb ist die eingegebene Versandfreigrenze erfüllt.</span>','good');const msg=gap<=fee?'Rechnerisch kann ein sinnvoller Zusatzartikel bis zur Schwellenlücke günstiger sein als die Versandkosten.':'Nur wegen der Versandfreigrenze zusätzlich zu kaufen wäre teurer als die Versandkosten.';result('shipResult',`<strong>Noch ${eur.format(gap)} bis zur Versandfreigrenze.</strong><span>Versand: ${eur.format(fee)}. ${msg}</span>`,gap<=fee?'good':'neutral')});
  $('useBtn')?.addEventListener('click',()=>{const buy=n($('useBuy').value),years=Math.max(1,n($('useYears').value)),uses=Math.max(1,n($('useUses').value)),annual=n($('useAnnual').value);if(buy<0)return result('useResult','Bitte gültige Werte eingeben.','bad');const total=buy+annual*years,count=uses*years;result('useResult',`<strong>${eur.format(total/count)} pro Nutzung</strong><span>Gesamtkosten ${eur.format(total)} über ${years} Jahr(e) bei ${count.toLocaleString('de-DE')} Nutzungen.</span>`,'good')});


  if($('barcodeResult')){const supported='BarcodeDetector' in window;result('barcodeResult',supported?'BarcodeDetector verfügbar. Foto wählen und lokal auswerten.':'Dieser Browser unterstützt BarcodeDetector derzeit nicht. Nutze den manuellen EAN/GTIN-Prüfer.','neutral');$('barcodeBtn')?.addEventListener('click',async()=>{const f=$('barcodeFile').files?.[0];if(!f)return result('barcodeResult','Bitte zuerst ein Bild auswählen.','bad');if(!('BarcodeDetector' in window))return result('barcodeResult','Barcode-Erkennung wird von diesem Browser nicht unterstützt.','bad');try{const detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','itf']});const bmp=await createImageBitmap(f);const codes=await detector.detect(bmp);bmp.close?.();if(!codes.length)return result('barcodeResult','Kein unterstützter Barcode erkannt.','bad');const vals=[...new Set(codes.map(x=>x.rawValue).filter(Boolean))];result('barcodeResult',`<strong>${vals.length} Barcode${vals.length===1?'':'s'} erkannt</strong><span>${vals.map(esc).join(' · ')}</span>`,'good')}catch(e){result('barcodeResult','Bild konnte nicht ausgewertet werden.','bad')}})}
  $('energyBtn')?.addEventListener('click',()=>{const w=n($('energyW').value),h=n($('energyHours').value),d=n($('energyDays').value),r=n($('energyRate').value),y=Math.max(1,n($('energyYears').value));if(w<0||h<0||d<0||r<0)return result('energyResult','Bitte gültige Werte eingeben.','bad');const kwh=w/1000*h*d,annual=kwh*r,total=annual*y;result('energyResult',`<strong>${eur.format(annual)} pro Jahr</strong><span>${kwh.toFixed(1).replace('.',',')} kWh/Jahr · ${eur.format(total)} über ${y} Jahr(e).</span>`,'good')});
  $('beBtn')?.addEventListener('click',()=>{const a=n($('beBuyA').value),ar=n($('beRunA').value),b=n($('beBuyB').value),br=n($('beRunB').value);if([a,ar,b,br].some(x=>x<0))return result('beResult','Bitte gültige Werte eingeben.','bad');const expensive=a>b?'A':'B',deltaBuy=Math.abs(a-b),saving=expensive==='A'?br-ar:ar-br;if(saving<=0)return result('beResult',`<strong>Kein Break-even durch die eingegebenen Betriebskosten.</strong><span>Das teurere Gerät ${expensive} spart pro Jahr nicht gegenüber dem günstigeren.</span>`,'neutral');const years=deltaBuy/saving;result('beResult',`<strong>Break-even nach ca. ${years.toFixed(1).replace('.',',')} Jahren</strong><span>Mehrpreis ${eur.format(deltaBuy)} · jährliche Ersparnis ${eur.format(saving)}.</span>`,'good')});

  const checks=['Produkt/Variante eindeutig identifiziert','Zustand der Ware geprüft','Lieferumfang vergleichbar','Versandkosten berücksichtigt','Menge/Packungsgröße vergleichbar','Tatsächlichen Verkäufer geprüft','Lieferbarkeit plausibel','Rückgabe-/Garantiebedingungen geprüft'];const box=$('buyChecklist');if(box){let saved={};try{saved=JSON.parse(localStorage.getItem('nbh_buycheck')||'{}')}catch{}checks.forEach((t,i)=>box.insertAdjacentHTML('beforeend',`<label class="check interactive-check"><input type="checkbox" data-i="${i}" ${saved[i]?'checked':''}><i>✓</i><div><b>${t}</b><span>${i===0?'Modell, Größe, Farbe, Speicher, Sprache oder GTIN beachten.':'Vor Abschluss kurz gegen das konkrete Angebot prüfen.'}</span></div></label>`));const update=()=>{const all=[...box.querySelectorAll('input')],done=all.filter(x=>x.checked).length;$('checkCount').textContent=`${done}/${all.length}`;$('checkProgress').style.width=`${done/all.length*100}%`;const o={};all.forEach(x=>o[x.dataset.i]=x.checked);localStorage.setItem('nbh_buycheck',JSON.stringify(o))};box.addEventListener('change',update);update();$('checkReset')?.addEventListener('click',()=>{box.querySelectorAll('input').forEach(x=>x.checked=false);localStorage.removeItem('nbh_buycheck');update()})}
});


document.addEventListener('DOMContentLoaded',()=>{const $=x=>document.getElementById(x),n=x=>{const v=parseFloat($(x)?.value);return Number.isFinite(v)?v:0},eur=new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}),set=(id,html,cls='good')=>{const e=$(id);if(!e)return;e.className='tool-result '+cls;e.innerHTML=html};$('finBtn')?.addEventListener('click',()=>{const total=n('finDown')+n('finMonthly')*Math.max(0,Math.floor(n('finMonths')))+n('finFinal')+n('finFees'),cash=n('finCash');if(total<=0)return set('finResult','Bitte Monatsrate und Laufzeit eintragen.','bad');const extra=cash>0?total-cash:null;set('finResult',`<strong>Gesamtzahlung: ${eur.format(total)}</strong><span>${cash>0?`Gegen Barpreis: ${extra>=0?eur.format(extra)+' Mehrkosten':eur.format(-extra)+' weniger'}.`:''} Reine Summenrechnung ohne Effektivzinsbewertung.</span>`)});$('cbBtn')?.addEventListener('click',()=>{const pay=Math.max(0,n('cbPrice')+n('cbShip')-n('cbCoupon')),eff=Math.max(0,pay-n('cbBack'));if(n('cbPrice')<=0)return set('cbResult','Bitte einen Preis größer 0 eingeben.','bad');set('cbResult',`<strong>Effektiver Preis: ${eur.format(eff)}</strong><span>Zahlbetrag vor Cashback: ${eur.format(pay)}. Cashback gilt erst nach tatsächlicher Auszahlung.</span>`)});$('subBtn')?.addEventListener('click',()=>{const m=Math.max(1,Math.floor(n('subMonths')||1)),total=n('subMonthly')*m+n('subOne'),buy=n('subBuy');if(n('subMonthly')<0)return;let s=`<strong>${eur.format(total)} über ${m} Monate</strong><span>${eur.format(total/m)} rechnerisch pro Monat.`;if(buy>0){const d=total-buy;s+=` Gegen Einmalkauf: ${d>=0?eur.format(d)+' mehr':eur.format(-d)+' weniger'}.`}s+='</span>';set('subResult',s)});$('vatBtn')?.addEventListener('click',()=>{const a=n('vatAmount'),r=n('vatRate')/100,mode=$('vatMode').value;if(a<0||r<0)return set('vatResult','Bitte gültige Werte eingeben.','bad');const gross=mode==='gross'?a:a*(1+r),net=mode==='gross'?a/(1+r):a,tax=gross-net;set('vatResult',`<strong>Brutto ${eur.format(gross)} · Netto ${eur.format(net)}</strong><span>Steueranteil bei eingegebenen ${(r*100).toFixed(1).replace('.',',')} %: ${eur.format(tax)}.</span>`)});$('urlCleanBtn')?.addEventListener('click',async()=>{const raw=$('urlCleanInput').value.trim();try{const u=new URL(raw),remove=['fbclid','gclid','dclid','msclkid','yclid','mc_cid','mc_eid'];[...u.searchParams.keys()].forEach(k=>{if(k.toLowerCase().startsWith('utm_')||remove.includes(k.toLowerCase()))u.searchParams.delete(k)});const clean=u.toString();set('urlCleanResult',`<strong>Bereinigte URL</strong><span class="clean-url">${clean.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</span><button type="button" class="mini-copy" id="copyCleanUrl">Kopieren</button>`);document.getElementById('copyCleanUrl').onclick=async()=>{try{await navigator.clipboard.writeText(clean);NBH?.toast?.('URL kopiert')}catch{}}}catch{return set('urlCleanResult','Die Eingabe ist keine gültige URL.','bad')}})});
