document.addEventListener('DOMContentLoaded',()=>{
const KEY='nbh_price_tracker_v1', eur=new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}), $=x=>document.getElementById(x), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}, save=a=>localStorage.setItem(KEY,JSON.stringify(a));
$('trackerDate').value=new Date().toISOString().slice(0,10);const preName=new URLSearchParams(location.search).get('name');if(preName)$('trackerName').value=preName;
function spark(obs){if(obs.length<2)return '<span class="muted">Noch kein Verlauf.</span>';const vals=obs.map(o=>o.price),min=Math.min(...vals),max=Math.max(...vals),w=260,h=66,pts=vals.map((v,i)=>`${i*(w/(vals.length-1))},${h-(max===min?h/2:(v-min)/(max-min)*(h-12)+6)}`).join(' ');return `<svg class="spark" viewBox="0 0 ${w} ${h}" role="img" aria-label="Preisverlauf"><polyline fill="none" stroke="currentColor" stroke-width="4" points="${pts}"/></svg>`}
function render(){const a=load();$('trackerCount').textContent=a.length;$('trackerList').innerHTML=a.length?a.map((x,i)=>{const vals=x.observations.map(o=>o.price),cur=vals.at(-1),lo=Math.min(...vals),hi=Math.max(...vals),hit=x.target>0&&cur<=x.target;return `<article class="tracker-card"><div class="tracker-top"><div><span class="tag">${hit?'Ziel erreicht':'Lokal beobachtet'}</span><h2>${esc(x.name)}</h2><p>${esc(x.merchant||'Kein Händler angegeben')}${x.url?` · <a class="read" href="${esc(x.url)}" target="_blank" rel="noopener">Link öffnen</a>`:''}</p></div><div class="tracker-price"><b>${eur.format(cur)}</b><span>min ${eur.format(lo)} · max ${eur.format(hi)}</span>${x.target>0?`<span>Ziel ${eur.format(x.target)}</span>`:''}</div></div><div class="tracker-chart">${spark(x.observations)}</div><div class="tracker-observe"><label>Neue Beobachtung<input type="number" step="0.01" min="0.01" data-p="${i}" placeholder="Preis in €"></label><label>Datum<input type="date" data-d="${i}" value="${new Date().toISOString().slice(0,10)}"></label><button class="btn btn-blue" data-add="${i}" type="button">Speichern</button><button class="btn btn-light" data-remove="${i}" type="button">Löschen</button></div><details><summary>${x.observations.length} Beobachtung(en)</summary><div class="history-list">${x.observations.slice().reverse().map(o=>`<span>${esc(o.date)} <b>${eur.format(o.price)}</b></span>`).join('')}</div></details></article>`}).join(''):'<div class="empty-state"><h2>Noch keine Preisbeobachtung</h2><p>Lege ein Produkt an und trage später neue Preise ein. Die Daten bleiben nur in diesem Browser.</p></div>';
$('trackerList').querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const i=+b.dataset.add,a=load(),p=parseFloat(document.querySelector(`[data-p="${i}"]`).value),d=document.querySelector(`[data-d="${i}"]`).value;if(!(p>0)||!d)return; a[i].observations.push({date:d,price:p});a[i].observations.sort((x,y)=>x.date.localeCompare(y.date));save(a);render()});$('trackerList').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const a=load();a.splice(+b.dataset.remove,1);save(a);render()});}
$('trackerForm').onsubmit=e=>{e.preventDefault();const name=$('trackerName').value.trim(),price=parseFloat($('trackerPrice').value),date=$('trackerDate').value;if(!name||!(price>0)||!date)return;const a=load();a.unshift({id:crypto.randomUUID?.()||Date.now().toString(36),name,merchant:$('trackerMerchant').value.trim(),url:$('trackerUrl').value.trim(),target:parseFloat($('trackerTarget').value)||0,createdAt:new Date().toISOString(),observations:[{date,price}]});save(a);e.target.reset();$('trackerDate').value=new Date().toISOString().slice(0,10);const preName=new URLSearchParams(location.search).get('name');if(preName)$('trackerName').value=preName;render()};
$('trackerCsv')?.addEventListener('click',()=>{const a=load(),rows=[['Produkt','Händler','URL','Zielpreis','Datum','Preis']];a.forEach(x=>x.observations.forEach(o=>rows.push([x.name,x.merchant||'',x.url||'',x.target||'',o.date,o.price])));const csv=rows.map(r=>r.map(v=>'\"'+String(v).replace(/\"/g,'\"\"')+'\"').join(';')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));link.download='nbhandel-preisbeobachtung.csv';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),500)});
render();});